INSERT INTO users ( username, password, first_name, last_name, email_address, address ) VALUES
		('elasticsnow', '$2b$11$pNxSnDbZxr/QEhsR7eIS7.gCJrA0S8PlBsQ1L33MARSg0P.PpUcK2', 'Mark', 'Rogers', 'm_rogers@hotmail.com', '329 Route 29'),
		('fiercetheory', '$2b$11$rviGVJz2HZJ.nE1AIzGmcOLSXKwe7H0qJ4bOQQaPSKTxU1DTcVnMq', 'Amanda', 'Perry', 'aaperry@aol.com', '445 Colonial Drive'),
		('faintrecess', '$2b$11$AH7iicbafR9AESMozqsVHuGTCmvlKbYOrGPVAEjUwDFeiGRigk6Gu', 'Joshua', 'Wright', 'joshua_wayne@aol.com', '470 Washington Avenue'),
		('stormyeye', '$2b$11$xBRK.DkqG9JcGn7yl22W6.iBcvSmEagq6H75vh4sCHXwmGqndvWBq', 'Andrew', 'Simmons', 'a_simmons@ymail.com', '8523 Charles Street'),
		('spikyvessel', '$2b$11$25JOVhHuHOUpKWAjokBjheTu0F.i18/W6Qjxf1G.mE6GfnZHU.H7m', 'Lillian', 'Adams', 'l_adams@yahoo.com', '85 Mulberry Street'),
		('spikyrainstorm', '$2b$11$F0bjueIlGASFeIRotMkav..ji/I.kmyisQ5wVPFjm8uzqP1lMx/T.', 'Nathan', 'Scott', 'nathan.alan.scott@rocketmail.com', '8897 Berkshire Drive'),
		('earthyframe', '$2b$11$MyU9zOu17ih2T8eYQcftR.lN84VIAjuylxH9od22goeQf9XgEeSdy', 'Jessica', 'Brooks', 'jessica.brooks@rocketmail.com', '96125 High Street'),
		('tallnose', '$2b$11$cdSKzxqMdSdDr5IErPC6fuLyx5eF1QQLQ1JJ.cl4MPMZNOs6KXdAS', 'Sophia', 'Bell', 's_bell11@live.com', '1805 Green Street'),
		('upsetcoat', '$2b$11$fuiMiLad1RqB.XiZgCAEIOnpCyhJ5O9wiH.EMOxz3/sjvUj/0P8Le', 'Jose', 'Taylor', 'jtaylor@aol.com', '26 Court Street'),
		('usedairplane', '$2b$11$2wTOULd0noNinFObK.yX3.ND7OjzHBeTdqFjegx.o/cViTUoObf.2', 'Jennifer', 'Jenkins', 'jennifer_jenkins@hotmail.com', '7301 Franklin Street'),
		('firstletter', '$2b$11$6UP8Lx0rw33r9Kj9/dmH7uPyhAYYqE2.eSULv4NJXwJ9wmYdBk0a2', 'Sean', 'Russell', 'seanrussell@rocketmail.com', '151 Sunset Drive'),
		('yellowrailway', '$2b$11$ckPgJDcOqmMs6Mltz.fSt.79Ihrth9kMWNwE4XSWyf.urFDTCS9aC', 'Alyssa', 'Walker', 'alyssa.rose@yahoo.com', '30 Summit Avenue'),
		('wickedcard', '$2b$11$mh4a6cdks6NBxNsbmMpcBOxdPTINiBoeSQhmSnV0iZDxX/3pP/i9i', 'Katherine', 'Rivera', 'katherine@rocketmail.com', '1241 Jefferson Avenue'),
		('chemicalrange', '$2b$11$JoMtDvvsW37vGCaPefeo7.mppHh31jtFFs7LVx6arLUGKUcCa/sTS', 'Gabriel', 'Thomas', 'g.s.thomas@live.com', '8996 South Street'),
		('productivewheel', '$2b$11$RIBTATZpFPq2Kw0GHszYo.VKN59c98MSNBYvTFT1pmXrGJZ5QH5cu', 'Daniel', 'Brown', 'daniel_henry_brown@hotmail.com', '46 Liberty Street'),
		('jollyticket', '$2b$11$7V9sbnPwVtlvPZfYKFxsIO4cEPxmWxiYHE1yrf1/iG2P6jEl6MaBy', 'Alexandra', 'Johnson', 'alexandra_m_johnson48@outlook.com', '40429 Clark Street'),
		('highfalutineye', '$2b$11$8fOpdZizeKAY/ELcLrfgLu4wsBGjSUBjjNQfzsbIhnbdQZtn24SaW', 'Daniel', 'Flores', 'd_flores@gmail.com', '81 Lincoln Street'),
		('mightykey', '$2b$11$xd6z/Z3vpi0ooZAC254in.OBVL8On/ERBEbBl4EeXnFq5d5Z9WjRW', 'Jose', 'Hughes', 'j_d_hughes@ymail.com', '97302 Summit Street'),
		('squealingwren', '$2b$11$75X8dXOz.zx69RSmh45yd.8KJQ4g.8Nf5bYYTjoOoYUtu75dWaPlW', 'Taylor', 'Lee', 'taylorllee@rocketmail.com', '70132 Route 32'),
		('openbulb', '$2b$11$18GsvVATyrUsjHSfE9.efOKiWBRiSvDXrfWsOtytELjLDCFXuLoPC', 'Olivia', 'Flores', 'o_flores@live.com', '477 Charles Street'),
		('quietsound', '$2b$11$9ARo4GlbVFfZS6i6djCkV.11YTiHDKI8QZLczt7GIPvj/EI0EgW1i', 'Brittany', 'White', 'brittany@outlook.com', '302 Hilltop Road'),
		('realsweater', '$2b$11$uwIiSCJzaFjII9U3RzkKheKRy/iHZoaIN0hItvrCOFQKfQWce/7Ae', 'Michelle', 'Miller', 'm_miller@outlook.com', '89183 Mulberry Street'),
		('animatedticket', '$2b$11$q1D.HhKvhLIsLQOiiV3P3.rpABTSaCi.f.qW5D9n7ambrS5Wjr1yi', 'Brian', 'Cook', 'brcook60@aol.com', '748 Chestnut Street'),
		('gulliblepin', '$2b$11$UYRXf2q5uyfav0.6GO0gVux/fiuKowVh3fhpZt4UgKDXAs3kAc6T.', 'Megan', 'Cook', 'm.m.cook@ymail.com', '46 Maple Avenue'),
		('clutteredsmile', '$2b$11$xbpmKBr0/2QgtON0qOkoTOQ7nHYCoRzwe6x11teAQ0WrvMXhjKIvS', 'Aubrey', 'Brown', 'aubreybrown24@ymail.com', '63273 Laurel Street'),
		('simplisticearth', '$2b$11$mvOPZuNuAZsLS1eG2C/qg.90XOJ4bsj6dYYUVtSUFjJVfKlr4OccG', 'Benjamin', 'Murphy', 'b.l.murphy@yahoo.com', '9537 11th Street'),
		('outgoingtrain', '$2b$11$CgbNrMGblbfJ6gDDyOJJEu/PSioMNGylsg8KgMLt0WtgIX3KAtFQe', 'Maria', 'Price', 'm_g_price@ymail.com', '5220 Dogwood Lane'),
		('mightybridge', '$2b$11$Z2hzcIdlWZ9wQbrtSioaEOnBekWREfUAA3jBfjO3wYjKT5Ayfqnyu', 'Julian', 'Kelly', 'julian_george55@live.com', '276 2nd Street'),
		('briefocean', '$2b$11$guKDnYRUfBZ.JC4I/wM1sOBxDq36CdKncDZeN7leDPqu6pVaNwpRO', 'Ryan', 'Turner', 'ryan.g.turner@outlook.com', '5647 Pine Street'),
		('unknowncamera', '$2b$11$L9dpTYkVw.98qdLvHZ/9vuI/TCl9JIusaW4gPWlCtmEzAVkQ.w3Wa', 'Courtney', 'Russell', 'courtney.russell96@yahoo.com', '8 Charles Street'),
		('crazymarket', '$2b$11$6lw4g1F90kaznx.YKV.kdutK/yKQMIsMNGQBKeifcm00PNmuUA3WK', 'Thomas', 'Hayes', 't_hayes@gmail.com', '9331 4th Street North'),
		('damagingstory', '$2b$11$vH/joQwoIlfgKTwu7bLMIeQlpFJqX.zBFh0ZuBt5baR67yl2RJecu', 'Charlotte', 'Rivera', 'charlotte.m.rivera55@rocketmail.com', '30 1st Street'),
		('realspring', '$2b$11$Iy/RNww62v/UzvXH79knFu.b1l7tyRoZv4WlLKfRcCsWHLVrDjCgm', 'Abigail', 'Collins', 'acollins@rocketmail.com', '51 Bridge Street'),
		('damagingshelf', '$2b$11$X31xaChL7Zq8Wam60X9Z7OIL42OuuKgChhcCjT2XrNyJ4H0Ckknb.', 'Henry', 'Cox', 'h_cox@gmail.com', '46 Hickory Lane'),
		('tenderticket', '$2b$11$UNLmgTqU5mpN5otr4caoxuMlYxZiQPO6l56wi7/T6JW9QDkHL4FDG', 'Victoria', 'Parker', 'victoria_parker@aol.com', '909 6th Avenue'),
		('equablehope', '$2b$11$apvdVfyHNI5zcO97CjQFlOpwfpaIxmY4qcKPCs4t.ocIPrF4K3WV6', 'Maria', 'Green', 'maria_green15@ymail.com', '56 2nd Street'),
		('knowledgeablestart', '$2b$11$QxHYkpTh0Bv8ZtTn9X0uKu.Ldk72NDZM0sDVDuipuRwAxlyis1K8O', 'Isabella', 'Rivera', 'isabellarivera@ymail.com', '376 Laurel Lane'),
		('elasticsteam', '$2b$11$ZwGX0fBTuxIaAhAa99tSsOUPFqYfjOZOGtePM2JR5rT4kEujaFWaC', 'Austin', 'Wood', 'awood@yahoo.com', '378 Laurel Street'),
		('standinghoney', '$2b$11$Up3qIAzCqtj5.FyotKVfdOtI2qx34/8whygq6WV7NMfce1WojeQdq', 'Rachel', 'Johnson', 'r_i_johnson@yahoo.com', '8932 Heather Lane'),
		('outgoingshade', '$2b$11$/FPITz2tPUJbDbnRDdSAj.eJRONEz3G1GFfAM2.9PGQGMEgW9a3z2', 'Sophia', 'Hernandez', 's.hernandez@rocketmail.com', '8809 11th Street'),
		('elasticbulb', '$2b$11$0BryQ9tFnSv3L2KPuKCRvu6YdQUWvEp1PIKV8R.MsQ4XbKBYsS2XS', 'Matthew', 'Smith', 'matthew67@ymail.com', '854 School Street'),
		('irateharbor', '$2b$11$5qULL4dvZRjhDUDfTKsdq.ac8GbUpMun1Cb1wQg/3Mjkvgq1Gurce', 'Daniel', 'Ramirez', 'd_ramirez@yahoo.com', '225 Main Street South'),
		('shytrip1234', '$2b$11$riL7rFD6L9LIGWWp70ytTO.fyyg71rlE0LrrLjUd/7W3hsJeXJav6', 'Mateo', 'Hughes', 'mhughes@aol.com', '7532 13th Street'),
		('colossalchicken', '$2b$11$L7sgzAia1fBEZ5JfWVjeEOGAvLXZjPwf7KAgl42diH9La.LqGUdDe', 'Heather', 'Rivera', 'heather.m.rivera7@gmail.com', '71921 Hillside Drive'),
		('shydegree', '$2b$11$H.q7unbI6236dKPg0DZlCuIrZsreWga0T9uvyBCQ1OeX48wg5fqzy', 'Zachary', 'Gray', 'z_gray@live.com', '2919 College Avenue'),
		('wanderingcard', '$2b$11$x7VZghrx5g.cEdCFzuL6gunVTmh/7lu9az6CleE0oDwhO61G18Thi', 'Maria', 'White', 'maria_white@hotmail.com', '8591 2nd Street East'),
		('simplisticactivity', '$2b$11$Zbyuj/yZexNQrQUk.CqnSOrhr/iSKVcSSIa.db5dfYl5Dyd.RBNUG', 'Abigail', 'Powell', 'abigail_lynn_powell@outlook.com', '75510 Charles Street'),
		('elasticstem', '$2b$11$509CZbDJ4eBBn/WBUid9oe2YAwGNtZ35.tkUPM1.ftFLoSZWAXeeS', 'Laura', 'Taylor', 'lntaylor@yahoo.com', '516 Valley Road'),
		('simplistictendency', '$2b$11$zXuEm5KUX.wg2JL2xzwkJeEKHKEfcW.lVxs78z0izn3SFhtFAuteu', 'David', 'Peterson', 'd_peterson@aol.com', '82966 1st Avenue'),
		('mysterioussuit', '$2b$11$m.NXbqT8zCJ0sULK9KEF2.Qw/p2MeianPQ0U8nZ2iAGpy1GdXtjtm', 'Stephanie', 'Simmons', 's.k@aol.com', '40503 2nd Avenue')
;
INSERT INTO credit_cards ( credit_card_number, ccv, user_id_fkey, expiration ) VALUES
		('3555264663306251', '848', 1, '0723'),
		('5336010754365644', '948', 2, '0523'),
		('633394720384097726', '455', 3, '0323'),
		('3554120196532865', '319', 4, '0124'),
		('3587119383780940', '122', 5, '0523'),
		('3544950927775471', '736', 6, '0124'),
		('304539605976770', '307', 7, '0124'),
		('3531612933991766', '859', 8, '0523'),
		('3538578353838055', '975', 9, '0623'),
		('3571305637456878', '757', 10, '0523'),
		('3569442318000404', '404', 11, '0124'),
		('3546725127287362', '903', 12, '0723'),
		('5107174993914823', '860', 13, '1223'),
		('50380656791829116', '365', 14, '0124'),
		('3570113653306493', '639', 15, '0423'),
		('3548145005731688', '849', 16, '1123'),
		('5100141919859371', '449', 17, '0623'),
		('5602235519975463', '936', 18, '0323'),
		('3581232638630962', '941', 19, '0523'),
		('560224723738354414', '100', 20, '0323'),
		('345764223403515', '141', 21, '0323'),
		('374288945934460', '702', 22, '1023'),
		('372301419791522', '711', 23, '0423'),
		('3556762038982184', '142', 24, '0323'),
		('5610500251672242', '877', 25, '0523'),
		('3528500215723152', '822', 26, '0323'),
		('3571396795824320', '688', 27, '0323'),
		('3568511220314367', '714', 28, '1023'),
		('373190087882799', '801', 29, '1023'),
		('5610864177334661', '806', 30, '0523'),
		('360771855393310', '943', 31, '0124'),
		('6334489402659709', '677', 32, '0223'),
		('5020463219320624', '988', 33, '0923'),
		('3553758055378440', '997', 34, '0923'),
		('304958605096330', '639', 35, '0623'),
		('3579204921245034', '887', 36, '0323'),
		('3534725974658107', '220', 37, '0923'),
		('560224036245052110', '599', 38, '1223'),
		('3549584819431540', '995', 39, '1123'),
		('5374538211888439', '874', 40, '1223'),
		('304973951660200', '811', 41, '0723'),
		('6761988939349215', '587', 42, '0124'),
		('501832760555288307', '768', 43, '0323'),
		('401795029573300', '331', 44, '1023'),
		('303255067326480', '341', 45, '0323'),
		('3553757545790362', '327', 46, '0523'),
		('3557548652903971', '351', 47, '0124'),
		('3553563967382823', '731', 48, '1223'),
		('3571935232148080', '256', 49, '0623'),
		('4041598041321270', '844', 50, '0124')
;
INSERT INTO authors ( first_name, last_name, biography ) VALUES
		('sarah', 'flores', 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Duis bibendum, odio id tristique luctus, lacus leo iaculis tellus, non venenatis enim massa euismod justo. Donec quis luctus risus. Pellentesque consectetur nisl ut scelerisque varius. Sed justo neque, mattis nec nibh non, vulputate hendrerit tellus. Fusce elementum consequat sem, nec ullamcorper dui mollis vitae. Pellentesque porttitor venenatis orci sit amet blandit. Duis sed dapibus orci, nec iaculis nisi. Aenean non sagittis elit. Sed sollicitudin eu ipsum vitae sodales. Integer interdum turpis ex, in vehicula magna consequat auctor. Phasellus vel lectus eget felis iaculis varius in eget velit. Donec ut urna varius, porta turpis ut, interdum massa. Sed non urna iaculis, ultrices ligula id, ultricies lacus. Proin semper efficitur nulla nec egestas. Curabitur a risus sed tortor consectetur aliquam.'),
		('mateo', 'baker', 'Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia curae; Suspendisse luctus luctus metus et eleifend. Donec pharetra sem congue elementum venenatis. Nulla vitae odio urna. Ut sit amet eros orci. Praesent dictum ac dui a efficitur. Ut non hendrerit velit, nec mattis dolor. Ut venenatis elit quam, eget pulvinar augue finibus sed. Proin mi magna, venenatis eu sagittis vel, porttitor vel velit. Pellentesque nisl lacus, aliquam quis turpis ac, congue mollis arcu. Suspendisse eu nunc consequat, tincidunt diam eget, ornare diam. Curabitur iaculis vitae erat in eleifend.'),
		('sebastian', 'howard', 'In semper urna sem, sagittis rutrum magna volutpat in. Vestibulum hendrerit vulputate euismod. Suspendisse ante erat, viverra et dui euismod, semper rhoncus neque. Aenean nulla neque, tempus condimentum faucibus a, dignissim eget magna. Proin ut imperdiet leo, commodo ultricies velit. Sed tempor ipsum eget enim convallis accumsan. Sed a tortor sit amet magna mollis porttitor non eget mauris. Fusce imperdiet augue id tellus laoreet, ac blandit ante ullamcorper. Quisque id varius risus. Sed ullamcorper id ligula at placerat.'),
		('christina', 'lewis', 'Nullam sollicitudin arcu eu dui facilisis, at tempor turpis scelerisque. Suspendisse faucibus volutpat lacus quis auctor. Praesent scelerisque nisl enim, a sodales elit aliquet ac. Sed viverra, eros quis varius cursus, sapien est aliquet metus, id malesuada orci felis vel risus. Praesent mattis, turpis et blandit sollicitudin, arcu nisl efficitur est, at imperdiet ante magna sit amet metus. Pellentesque faucibus quam fermentum, viverra est a, pellentesque tellus. Morbi sed mauris tellus. Suspendisse potenti. Nullam sit amet augue vitae orci tempus rhoncus.'),
		('charles', 'simmons', 'Curabitur fringilla lacus ac lacus dignissim condimentum mollis in est. Aliquam consectetur, nulla et accumsan eleifend, erat tellus cursus nulla, at faucibus libero lacus nec ante. Aliquam et ex at lorem ornare mollis. In hac habitasse platea dictumst. Aenean pretium viverra eros, at mattis libero. Proin vel dui et ex interdum dapibus. Etiam sit amet porta diam, at interdum enim. Vivamus in est et elit dignissim dignissim. Nam augue augue, pharetra non sagittis in, convallis vitae lectus. Curabitur vulputate massa nec elit feugiat volutpat. Integer accumsan rutrum risus vel dictum. Pellentesque ornare ipsum sed bibendum mollis. Cras enim elit, dignissim eget enim vel, sagittis rutrum purus. Nulla ut laoreet massa, pretium tincidunt quam.'),
		('sara', 'baker', 'Fusce at nunc lacinia, bibendum neque in, pharetra elit. Fusce orci justo, elementum vel mi sit amet, ultrices tempor eros. Ut placerat massa et velit tempor, id congue urna mollis. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Etiam dignissim neque non mattis blandit. Integer eget placerat erat. Donec tempor lorem ipsum, sed imperdiet sem rhoncus vel. Nullam nulla ligula, malesuada quis enim vel, ultrices dapibus mauris. In et justo non elit molestie dapibus sed eu velit. Donec semper, orci ut cursus egestas, nibh urna fringilla tortor, a blandit tellus libero vitae massa. Suspendisse fermentum ex vel volutpat luctus. Etiam ut venenatis leo.'),
		('aiden', 'gray', 'Sed nec dictum sem. Pellentesque dictum ante ac quam lobortis placerat. Suspendisse consectetur, sapien consectetur ornare venenatis, ante quam mollis lorem, a vehicula est enim sed quam. Etiam volutpat lacus diam, in elementum erat pharetra eget. Pellentesque lacus nisi, dapibus non volutpat non, lacinia nec nulla. Fusce eget purus suscipit, sagittis lacus sed, posuere mauris. Vivamus porttitor elementum iaculis. Nam id iaculis erat. Maecenas sit amet leo a magna aliquam suscipit id ut dolor. Cras vulputate nisl a scelerisque bibendum. In condimentum viverra congue. Fusce vitae ex vitae dolor venenatis aliquet. Vivamus id blandit lectus, eget vehicula nulla. Quisque laoreet ullamcorper consequat. Donec vitae risus vel lacus eleifend scelerisque.'),
		('patrick', 'adams', 'Vivamus eu lacus magna. Fusce sollicitudin maximus ante sed semper. Nulla facilisi. Suspendisse ultricies mi eget nisi vehicula, at aliquam nunc interdum. Nulla neque tellus, ultrices non consequat vitae, vehicula vulputate orci. Vivamus iaculis urna non enim maximus condimentum. Aliquam porttitor egestas viverra. Suspendisse elementum magna mauris, vitae vestibulum orci porttitor quis. Interdum et malesuada fames ac ante ipsum primis in faucibus. Pellentesque vehicula efficitur libero. In bibendum scelerisque lectus, sed vulputate diam gravida nec. Nulla congue bibendum velit dictum pulvinar. Cras pharetra libero a tempor tincidunt. Mauris eget ullamcorper nibh.'),
		('kimberly', 'hall', 'Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Curabitur volutpat nisl ut arcu fermentum, sit amet commodo lectus viverra. Aliquam erat volutpat. Vestibulum dui mauris, sagittis sit amet tristique eget, pellentesque non nibh. Aliquam sollicitudin, ante vel varius finibus, urna velit sagittis enim, id auctor dui ligula in urna. Mauris ornare convallis sem in dictum. Aliquam et ante sed nisl blandit imperdiet vel vel libero. Morbi imperdiet dui vestibulum dolor tincidunt mattis ac ut diam. Nullam aliquet sodales ligula vel fringilla. Suspendisse velit nibh, finibus at elit sit amet, blandit condimentum leo. Vestibulum viverra non elit nec ornare. In id tortor lectus. Donec non lectus quis tellus ultrices cursus. Quisque tincidunt ligula in est lacinia, non malesuada risus semper. Donec varius augue ut tellus porta interdum sit amet in diam. Maecenas posuere, tortor at condimentum volutpat, nisl odio pulvinar sapien, et vehicula nunc urna at tortor.'),
		('jose', 'garcia', 'Phasellus eget fringilla justo. Integer sem mauris, viverra non ligula sagittis, consectetur pharetra tortor. Donec et varius leo. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Etiam pharetra mollis ante, eget vestibulum turpis vestibulum vel. Donec dictum, tellus vitae fermentum egestas, erat leo tristique orci, ut aliquet lectus massa sed mauris. Integer viverra hendrerit nisl a vulputate. Pellentesque finibus auctor nisl, nec aliquet magna cursus ut.'),
		('mark', 'williams', 'Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Curabitur volutpat nisl ut arcu fermentum, sit amet commodo lectus viverra. Aliquam erat volutpat. Vestibulum dui mauris, sagittis sit amet tristique eget, pellentesque non nibh. Aliquam sollicitudin, ante vel varius finibus, urna velit sagittis enim, id auctor dui ligula in urna. Mauris ornare convallis sem in dictum. Aliquam et ante sed nisl blandit imperdiet vel vel libero. Morbi imperdiet dui vestibulum dolor tincidunt mattis ac ut diam. Nullam aliquet sodales ligula vel fringilla. Suspendisse velit nibh, finibus at elit sit amet, blandit condimentum leo. Vestibulum viverra non elit nec ornare. In id tortor lectus. Donec non lectus quis tellus ultrices cursus. Quisque tincidunt ligula in est lacinia, non malesuada risus semper. Donec varius augue ut tellus porta interdum sit amet in diam. Maecenas posuere, tortor at condimentum volutpat, nisl odio pulvinar sapien, et vehicula nunc urna at tortor.'),
		('jennifer', 'roberts', 'Suspendisse facilisis, magna quis laoreet interdum, ligula elit porta augue, nec malesuada eros sapien eu nisl. In sed lacus ac mi placerat congue. Suspendisse massa orci, iaculis id facilisis tempus, gravida in est. Vestibulum eu lacus eget massa dignissim efficitur vitae malesuada leo. Quisque ultricies massa turpis, quis venenatis justo vehicula vel. Donec eu cursus turpis. Aliquam vel vulputate eros, eget faucibus elit. Phasellus vel egestas orci, vel cursus neque. Suspendisse feugiat sapien orci. Curabitur rhoncus ultricies laoreet. In vitae euismod tortor, sed rutrum lorem. Vivamus at augue scelerisque, bibendum est vel, aliquam ligula. Aliquam sagittis ornare neque, sed fermentum nisi cursus ut. Donec purus arcu, convallis eget eros dapibus, euismod malesuada diam. Vivamus congue, metus in fringilla facilisis, ante orci posuere turpis, nec malesuada massa nisi dignissim mi. Donec sed augue lectus.'),
		('amber', 'diaz', 'Praesent sit amet sem tempor, blandit risus id, aliquam metus. Fusce convallis consequat sodales. Nam dignissim consequat finibus. Sed condimentum finibus neque, ut tincidunt ipsum lobortis vel. Vivamus sed rutrum nisl, sed hendrerit ipsum. Nullam volutpat ut dui nec gravida. In non malesuada tortor. Nullam gravida nulla vel ante condimentum volutpat. Donec et odio ac leo elementum lacinia. Integer consequat vulputate dolor a maximus. Maecenas ut commodo lacus. Donec dictum est nec auctor condimentum. Nam maximus dapibus lacus ut ultricies. Praesent vulputate dapibus risus, quis suscipit arcu pellentesque eget. Nam malesuada lorem ut lacus tincidunt, id pellentesque velit pulvinar. Nulla facilisi.'),
		('timothy', 'griffin', 'Vestibulum tristique quam eget neque euismod luctus. Suspendisse nec ex justo. Nam vehicula metus et luctus consequat. Aenean sed arcu luctus nibh laoreet pulvinar eget quis dolor. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. In vitae dui mi. Suspendisse sit amet luctus lacus. Nunc placerat tempor ipsum. Cras pellentesque nunc at libero scelerisque, id ultricies turpis sagittis. Etiam vitae nisl vitae turpis vestibulum mollis eget non risus.'),
		('isabella', 'lewis', 'Nam nisl ligula, euismod a turpis sed, ornare commodo odio. Vivamus nec nisl eget libero finibus posuere. Etiam ac libero lacinia, maximus arcu id, maximus diam. Aliquam venenatis nunc justo, at dignissim arcu bibendum non. Sed in enim at felis tempus dictum sed vel mi. Duis at arcu non leo facilisis ullamcorper in sit amet orci. Mauris et libero tincidunt, congue magna ut, gravida dui. Maecenas augue risus, mattis fringilla facilisis nec, maximus sed ligula. Curabitur sit amet felis ac tellus blandit sagittis vel eget arcu. Morbi libero nulla, mattis sed tincidunt eu, laoreet a mauris. Sed ut leo ultricies, eleifend est ut, pellentesque eros.'),
		('alexandra', 'torres', 'Sed volutpat porttitor arcu, ac condimentum ligula. Aenean quis imperdiet mauris. Morbi sagittis sodales justo, ac auctor felis sagittis pulvinar. Cras sed arcu tempus, facilisis nisl vitae, convallis sem. Mauris odio dolor, maximus vel auctor et, molestie sed magna. Pellentesque vel ultrices felis. Cras et pulvinar lorem. Nunc dignissim maximus varius. Sed et diam volutpat nisi aliquet tempor. Phasellus non ligula congue, bibendum nisl et, viverra nulla. Maecenas ut lorem quis mi tempor finibus at sit amet dolor. Proin auctor urna sed erat lacinia, et aliquam lacus hendrerit. Cras diam sapien, dapibus non mi nec, pretium lobortis diam. Duis interdum lacinia felis, ultrices venenatis ex pharetra sit amet. Vestibulum sollicitudin dignissim mauris, vitae aliquet nisi vestibulum vitae.'),
		('william', 'martinez', 'Ut molestie mollis urna in lobortis. Pellentesque id massa arcu. Pellentesque gravida, quam quis consequat consequat, erat elit faucibus nulla, vel condimentum est nulla ac ligula. Praesent sed ligula dolor. Fusce elementum semper odio, sit amet imperdiet ipsum tincidunt id. Mauris et lectus in velit tristique lacinia. Phasellus rutrum lacus quis sagittis pharetra. Morbi malesuada tellus sed felis euismod, id fringilla arcu posuere. Nunc rutrum dapibus odio vel efficitur. Pellentesque quis dignissim est. Morbi aliquet dui id ex efficitur tincidunt. Maecenas varius diam sit amet eros volutpat, tempor efficitur urna ornare.'),
		('rebecca', 'wood', 'Nunc vitae luctus nibh. Nam accumsan, risus sit amet finibus tristique, nibh libero efficitur dolor, vel lobortis tortor ligula sed nunc. Sed mattis eu orci et fringilla. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nam suscipit felis nunc, in pharetra nibh consectetur in. Quisque mattis tortor quis mattis tempus. Proin vestibulum porttitor luctus. Cras ligula nulla, dignissim at ultrices quis, dapibus at ante. Donec porta ex libero, id fringilla ipsum ornare in. Curabitur ex nibh, ullamcorper ut sollicitudin eget, lacinia eget dolor.'),
		('jessica', 'mitchell', 'Morbi ac ligula auctor, dictum orci ac, malesuada est. Nullam malesuada nulla tellus, a condimentum nulla pulvinar vel. Nunc cursus posuere sapien ut scelerisque. Suspendisse eget facilisis nibh, nec sollicitudin massa. Nulla facilisi. In sollicitudin, tellus nec vehicula luctus, sem lacus cursus felis, ac fringilla ante nisi ac sapien. Sed venenatis maximus bibendum. Quisque erat odio, laoreet ac molestie sed, molestie cursus ligula. Nam ac magna id erat placerat hendrerit.'),
		('abigail', 'hughes', 'Vivamus eu leo vitae massa accumsan fermentum eu a mauris. Sed sit amet ex eros. Ut interdum laoreet elementum. Donec quis elit sit amet justo porttitor condimentum et nec urna. Integer ultricies viverra ipsum id luctus. Aliquam quis euismod felis. Ut varius sapien felis, sed maximus nisl molestie id.'),
		('lillian', 'parker', 'Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia curae; Suspendisse luctus luctus metus et eleifend. Donec pharetra sem congue elementum venenatis. Nulla vitae odio urna. Ut sit amet eros orci. Praesent dictum ac dui a efficitur. Ut non hendrerit velit, nec mattis dolor. Ut venenatis elit quam, eget pulvinar augue finibus sed. Proin mi magna, venenatis eu sagittis vel, porttitor vel velit. Pellentesque nisl lacus, aliquam quis turpis ac, congue mollis arcu. Suspendisse eu nunc consequat, tincidunt diam eget, ornare diam. Curabitur iaculis vitae erat in eleifend.'),
		('oliver', 'garcia', 'Pellentesque fermentum facilisis hendrerit. Vivamus venenatis dapibus sem, sit amet placerat tortor blandit eget. Nullam id augue vitae nulla interdum pharetra ut et turpis. Etiam nisl mauris, feugiat malesuada mi sed, vestibulum commodo lectus. Donec convallis ac tortor vitae tincidunt. Praesent ut ligula elit. Morbi eget mi ex. Curabitur quis dignissim eros. Suspendisse id massa at velit maximus ultrices. Suspendisse euismod rhoncus sapien, sit amet pretium arcu mollis a. Cras commodo lacus erat, gravida congue ipsum condimentum nec. In lacinia nunc sagittis mauris ullamcorper interdum. Pellentesque ac risus consequat orci congue malesuada in nec mi. Donec eleifend id nunc quis semper. Sed consequat metus non accumsan rutrum.'),
		('olivia', 'robinson', 'Vestibulum lacinia massa nec viverra vulputate. Cras a ante sem. Morbi interdum lobortis lacus id ullamcorper. Integer pellentesque fringilla libero quis cursus. Curabitur vitae dictum nibh, non accumsan turpis. Quisque aliquam nec nibh a aliquam. Curabitur nunc arcu, rutrum eget mattis id, semper in mi. In arcu augue, commodo sit amet finibus eget, dignissim in quam. Nulla sollicitudin enim in nibh venenatis, in cursus dui hendrerit. Morbi at mollis nulla.'),
		('kevin', 'johnson', 'In molestie tortor sit amet orci dapibus, sed pellentesque velit laoreet. Suspendisse blandit mauris finibus sapien pulvinar, nec bibendum ligula tempus. Praesent vitae maximus quam. Morbi at mattis lorem. Nullam cursus consectetur odio, eget convallis ante semper id. Praesent eget velit quam. Nulla et lectus tellus. Aliquam ultrices, est vitae vestibulum scelerisque, urna purus vulputate neque, eu laoreet quam sapien non massa. Nam porttitor sagittis elementum. Cras posuere fermentum justo, at mollis ipsum semper a. Donec id suscipit ipsum, eu ullamcorper turpis. Aenean laoreet nulla id quam fermentum facilisis. Vivamus mauris quam, accumsan at metus ut, ullamcorper luctus sem. Suspendisse in purus semper, suscipit urna nec, tempus lorem. Vivamus venenatis tempus nulla. Mauris sem erat, fringilla id lectus sit amet, vestibulum tempor arcu.'),
		('steven', 'hall', 'Proin in neque vel lorem tincidunt laoreet eget faucibus est. Aenean scelerisque lectus vel tellus tempor vestibulum. Etiam gravida purus porta arcu luctus pharetra. Curabitur nec nibh metus. Sed eu nisl gravida, maximus nulla nec, bibendum ligula. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos. Ut consequat dolor vel lorem eleifend pulvinar. Vestibulum tempor dictum felis non condimentum. Suspendisse nec risus non felis sollicitudin consectetur. Sed at lorem vitae turpis faucibus sollicitudin. Integer diam nunc, euismod ac ornare sed, cursus et ante. Donec lobortis lorem eget est sodales gravida. Aenean tempor elit et venenatis imperdiet. Donec ornare tempus mauris et facilisis.'),
		('haley', 'brown', 'Proin ut ex nec magna blandit maximus ac in magna. Sed lacinia maximus lacinia. Sed sollicitudin, sem non efficitur dictum, dui sapien sagittis neque, a rutrum turpis est eget neque. Suspendisse quis lorem a tellus volutpat tincidunt. In cursus lacus quis sem euismod, eu ultrices diam aliquam. Vivamus tellus mi, ullamcorper et volutpat sed, consequat quis ipsum. Pellentesque bibendum et dui non efficitur. Sed a feugiat erat, id iaculis leo.'),
		('stephen', 'adams', 'Vestibulum tristique quam eget neque euismod luctus. Suspendisse nec ex justo. Nam vehicula metus et luctus consequat. Aenean sed arcu luctus nibh laoreet pulvinar eget quis dolor. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. In vitae dui mi. Suspendisse sit amet luctus lacus. Nunc placerat tempor ipsum. Cras pellentesque nunc at libero scelerisque, id ultricies turpis sagittis. Etiam vitae nisl vitae turpis vestibulum mollis eget non risus.'),
		('brianna', 'perez', 'Pellentesque dictum ante vitae tempor sodales. Phasellus sed egestas felis, id sagittis ipsum. Sed pharetra non urna quis luctus. Aenean iaculis iaculis augue, eget rutrum justo aliquet dapibus. Proin convallis vel tellus a bibendum. Duis sagittis ultrices orci vitae feugiat. Donec vehicula cursus diam at varius. Sed non varius nunc, at gravida est. Cras sodales varius metus ut dignissim. In hac habitasse platea dictumst. Aliquam diam quam, consequat et vestibulum vel, elementum nec elit. Nulla et viverra felis. In eget dolor non metus fermentum scelerisque.'),
		('laura', 'wood', 'Curabitur tristique vehicula vestibulum. Etiam blandit dictum ex, malesuada commodo lectus gravida ac. Morbi a augue quam. Aenean volutpat condimentum efficitur. Nunc ut purus vestibulum, tincidunt nunc in, congue ante. Sed consequat felis sed elementum semper. Curabitur tincidunt mollis lacus, sit amet tincidunt eros sodales sit amet. Maecenas condimentum eros eget vestibulum aliquam. Phasellus sapien lorem, mollis vel lectus vel, bibendum fermentum ligula. Morbi sollicitudin suscipit felis, a commodo justo fringilla id.'),
		('chelsea', 'parker', 'Donec sed enim nulla. Phasellus molestie justo a metus pellentesque finibus. Vivamus justo nulla, tempus et magna et, cursus scelerisque turpis. Curabitur vulputate quam sit amet orci semper, vel efficitur ipsum tempor. Donec a sapien dictum, porttitor nibh ut, tempus urna. Nunc vel dignissim mauris. Nam sit amet purus id velit imperdiet luctus et ut lorem. Aenean dignissim urna et ante ullamcorper, eget finibus lorem feugiat. Curabitur dapibus ultricies felis, vel ullamcorper erat ultrices eu.'),
		('brianna', 'hall', 'Suspendisse ac nibh lacinia, maximus magna id, auctor erat. Proin auctor ultrices erat, id blandit arcu maximus vitae. Phasellus eu urna sapien. Vestibulum ornare arcu est. Integer viverra venenatis mauris, a pharetra dolor accumsan a. Nunc porta egestas arcu. Nunc quis odio id augue scelerisque finibus. Donec ultrices in felis in tincidunt. Integer pharetra massa at aliquet vestibulum. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nullam aliquet justo eu tortor vehicula tincidunt. Vestibulum commodo, purus sit amet sollicitudin tincidunt, eros nibh lobortis massa, at blandit lectus turpis quis nulla. Proin accumsan tortor euismod tincidunt fringilla. Nunc a augue ante. Proin posuere dolor non turpis mattis varius. Suspendisse porttitor ornare rhoncus.'),
		('sebastian', 'morris', 'Praesent ut nibh vitae eros vestibulum semper. Vivamus sed ligula sit amet justo placerat vulputate. Quisque faucibus aliquet dolor. Proin mattis turpis sed tempor cursus. Aliquam laoreet leo quam, eu tincidunt dolor consectetur sed. Sed congue vehicula lectus, sed iaculis felis rhoncus sit amet. Integer efficitur viverra sapien, sed venenatis eros sagittis at. In consectetur libero id mauris malesuada lobortis. Proin dignissim orci urna, eget congue ipsum pharetra sed. Integer sagittis congue diam, eget volutpat lacus luctus sit amet. Etiam viverra, lacus ac mollis suscipit, eros enim varius metus, a pulvinar velit nunc congue sapien. Sed id congue augue.'),
		('amber', 'richardson', 'Nunc vitae luctus nibh. Nam accumsan, risus sit amet finibus tristique, nibh libero efficitur dolor, vel lobortis tortor ligula sed nunc. Sed mattis eu orci et fringilla. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nam suscipit felis nunc, in pharetra nibh consectetur in. Quisque mattis tortor quis mattis tempus. Proin vestibulum porttitor luctus. Cras ligula nulla, dignissim at ultrices quis, dapibus at ante. Donec porta ex libero, id fringilla ipsum ornare in. Curabitur ex nibh, ullamcorper ut sollicitudin eget, lacinia eget dolor.'),
		('jonathan', 'diaz', 'Donec elementum volutpat porttitor. Phasellus eget lectus vitae neque convallis accumsan. Cras aliquam lobortis metus id pulvinar. Pellentesque ut volutpat augue. Phasellus feugiat tristique est, vitae laoreet libero maximus quis. Nam fringilla aliquet tellus ac pretium. Quisque pulvinar augue eget nunc mollis, nec luctus ex lobortis. Phasellus a sagittis justo. Cras placerat sem in eros bibendum dapibus et ut nulla. Nulla cursus libero odio, vel volutpat diam vulputate eu. Proin id dolor dolor. Integer ut vehicula odio, eget rhoncus tellus. Integer quis tristique magna, eu fringilla lorem. Cras vehicula, justo sit amet congue fringilla, quam augue interdum nulla, at pretium massa tellus in arcu. Pellentesque vel suscipit metus.'),
		('rachel', 'butler', 'Nunc nec ante et metus malesuada blandit. Nullam eleifend nisl sed leo bibendum, quis laoreet massa vestibulum. Quisque vestibulum libero tempus nibh tincidunt, eget tempor turpis euismod. Donec dictum molestie mauris ac molestie. Mauris at fringilla augue, nec varius nibh. Morbi ultrices et neque eu suscipit. Aenean sagittis nisl eu dapibus semper. Praesent fermentum semper odio commodo euismod. Donec quis gravida lorem, vel ornare nunc. Ut venenatis id orci quis vehicula. Sed tortor ex, egestas a tempus id, sagittis at nulla.'),
		('heather', 'jenkins', 'Aenean id posuere urna. Phasellus vehicula est ex, elementum consequat dui ornare non. Suspendisse libero risus, vulputate vitae ultricies nec, placerat ac tortor. Donec tincidunt ornare metus. Nunc nunc dolor, egestas in odio in, mattis facilisis est. Sed ac ligula eget orci consectetur interdum. Fusce elit metus, consequat ut tortor sit amet, porttitor feugiat nisl. Donec tempus maximus purus et ultricies. Nunc pretium elit non felis placerat placerat. Suspendisse cursus diam nulla, eu pellentesque ipsum viverra at. Nulla sit amet maximus lorem.'),
		('nicole', 'parker', 'Sed nec dictum sem. Pellentesque dictum ante ac quam lobortis placerat. Suspendisse consectetur, sapien consectetur ornare venenatis, ante quam mollis lorem, a vehicula est enim sed quam. Etiam volutpat lacus diam, in elementum erat pharetra eget. Pellentesque lacus nisi, dapibus non volutpat non, lacinia nec nulla. Fusce eget purus suscipit, sagittis lacus sed, posuere mauris. Vivamus porttitor elementum iaculis. Nam id iaculis erat. Maecenas sit amet leo a magna aliquam suscipit id ut dolor. Cras vulputate nisl a scelerisque bibendum. In condimentum viverra congue. Fusce vitae ex vitae dolor venenatis aliquet. Vivamus id blandit lectus, eget vehicula nulla. Quisque laoreet ullamcorper consequat. Donec vitae risus vel lacus eleifend scelerisque.'),
		('sara', 'jenkins', 'Ut molestie mollis urna in lobortis. Pellentesque id massa arcu. Pellentesque gravida, quam quis consequat consequat, erat elit faucibus nulla, vel condimentum est nulla ac ligula. Praesent sed ligula dolor. Fusce elementum semper odio, sit amet imperdiet ipsum tincidunt id. Mauris et lectus in velit tristique lacinia. Phasellus rutrum lacus quis sagittis pharetra. Morbi malesuada tellus sed felis euismod, id fringilla arcu posuere. Nunc rutrum dapibus odio vel efficitur. Pellentesque quis dignissim est. Morbi aliquet dui id ex efficitur tincidunt. Maecenas varius diam sit amet eros volutpat, tempor efficitur urna ornare.'),
		('timothy', 'rodriguez', 'Sed non fermentum erat, et venenatis ipsum. Aliquam eleifend imperdiet volutpat. Aliquam egestas ipsum mauris, et commodo dui consectetur quis. Vestibulum rhoncus nulla quis feugiat interdum. In imperdiet purus metus, id condimentum lectus ultricies vel. Curabitur ut interdum nisi. In sed nunc suscipit, luctus mauris eu, congue sapien. Suspendisse ornare quis odio eget suscipit. In accumsan urna nunc, non mattis enim blandit ut. In ut libero orci. Ut semper velit ut elit ullamcorper, ac vulputate libero rutrum. Praesent justo leo, eleifend a molestie vestibulum, bibendum sit amet leo. Sed interdum et tortor ut laoreet. Nulla in tellus augue. Aenean sit amet felis id purus commodo auctor id non odio. Donec interdum, lorem consectetur condimentum mollis, mauris sem pretium turpis, sed faucibus magna tortor a erat.'),
		('mark', 'walker', 'Vestibulum lacinia massa nec viverra vulputate. Cras a ante sem. Morbi interdum lobortis lacus id ullamcorper. Integer pellentesque fringilla libero quis cursus. Curabitur vitae dictum nibh, non accumsan turpis. Quisque aliquam nec nibh a aliquam. Curabitur nunc arcu, rutrum eget mattis id, semper in mi. In arcu augue, commodo sit amet finibus eget, dignissim in quam. Nulla sollicitudin enim in nibh venenatis, in cursus dui hendrerit. Morbi at mollis nulla.'),
		('eric', 'stewart', 'Duis sodales dignissim leo vitae convallis. Praesent rhoncus pulvinar lectus quis suscipit. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia curae; Nunc ut elementum neque. Cras est ipsum, molestie vel vulputate vulputate, iaculis ac tellus. Nulla consectetur non ante et auctor. Etiam sodales lectus vel lectus scelerisque pretium ut sed felis. Maecenas congue felis vitae sapien dignissim rutrum. Proin in mi ex.'),
		('brittany', 'collins', 'Pellentesque iaculis turpis felis, eu vestibulum tellus molestie ut. Orci varius natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Phasellus molestie, nisi sit amet blandit gravida, felis libero ultrices risus, vel tincidunt nulla dolor sed ipsum. Integer est tortor, laoreet vitae neque eget, maximus bibendum lacus. Quisque odio ante, faucibus id sem a, vehicula elementum magna. Donec egestas id ligula eu euismod. Nullam aliquam justo a arcu malesuada, sed pulvinar mauris luctus. Nunc egestas elementum laoreet. Sed accumsan pretium interdum. Praesent maximus cursus imperdiet. Vestibulum libero purus, finibus eu maximus a, fermentum eget ex.')
;
INSERT INTO publishers ( publisher_name, discount_percent ) VALUES
		('Philadelphia : J.B. Lippincott', 3),
		('Tours : A. Mame', 6),
		('Oakland, City art printing company', 9),
		('Dorset : The Author', 12),
		('London : Chapman & Hall', 15),
		('New York, London : M. Kennerley', 18),
		('New York : J. Lane Co.,1916', 21),
		('New York : Harper', 24),
		('New York : Grosset & Dunlap', 27),
		('New York : A. D. F. Randolph & company', 30)
;
INSERT INTO genres ( genre_name ) VALUES
		('documentary'),
		('comedy'),
		('war'),
		('animation'),
		('drama'),
		('action'),
		('fantasy'),
		('sci-fi'),
		('crime'),
		('horror')
;
INSERT INTO books ( copies_sold, isbn, publisher_id_fkey, book_name, book_price, genre_id_fkey, author_id_fkey, year_published, book_description ) VALUES
		(552, '1048335068', 1, 'Life of Philip Doddridge, D. D. : with notices of some of his contemporaries, and specimens of his style', 1104, 1, 1, 1869, '249 p. : 19 cm'),
		(479, '1048209812', 2, 'Le Dahomé, souvenirs de voyage et de mission', 958, 2, 2, 1880, '239 p'),
		(337, '1048316853', 3, 'The liberator ..', 674, 3, 3, 1915, '2 p. l., [9]-105 p., 3 l. 18 cm'),
		(361, '1048299273', 4, 'Liberty; a study in comparative philology', 722, 4, 4, 1911, '19 p Reproduced from handwritten copy'),
		(800, '1157905345', 5, 'Travels, sport, and politics in the east of Europe', 1600, 5, 5, 1887, 'viii p., 2 l., 311 p. 21 cm'),
		(468, '1085980142', 6, 'The true adventures of a play', 936, 6, 6, 1914, '182 p. 20 cm'),
		(348, '1047522719', 7, 'In spacious times', 696, 7, 7, 1916, '338 p'),
		(321, '9695157500', 8, 'The institutes of medicine', 642, 8, 8, 1870, 'Includes index'),
		(594, '1047428651', 9, 'Infatuation', 1188, 9, 9, 1909, '380 p., [4] leaves of plates : 20 cm'),
		(479, '1102114055', 10, 'Voices from a busy life; or, Selections from the poetical works of the late Edward A. Washburn', 958, 10, 10, 1883, '186 p. 19 cm Preface signed: Wm. Wilberforce Newton Translations of ancient Christian hymns: p. [121]-186'),
		(389, '1158277616', 1, 'Vom Bismarck der 70er jahre', 778, 1, 11, 1920, 'iv, 121 p. 24 cm'),
		(432, '7617751830', 2, 'The Wabash trade route in the development of the old Northwest', 864, 2, 12, 1903, '112 p. 25 cm'),
		(963, '1102238531', 3, 'Vienna International Exhibition, 1873. Report on deaf-mute instruction', 1926, 3, 13, 1875, '9 p. ; 24 cmOn cover: Department of StateIncludes index'),
		(468, '1158273407', 4, 'The virtuous Octavia, 1598', 936, 4, 14, 1909, 'ix, 126 p. 22 cm Original book_name: The tragi comoedi of the vertuous Octauia. Done by Samvel Brandon. 1598.. Followed by two letters (in verse) between Octavia and Antony, dedicated to Mistresse Mary Thinne. Prepared by Ronald B. McKerrow and ... the general editor W. W. Greg.'),
		(573, '1158272741', 5, 'The way of the strong;', 1146, 5, 15, 1914, 'vii, 447 p'),
		(482, '1158274408', 6, 'Wanted, a tortoise-shell', 964, 6, 16, 1917, '312 p. ; 19 cm'),
		(481, '1158278730', 7, 'War poems', 962, 7, 17, 1867, '59 p. 18 cm'),
		(343, '1102189976', 8, 'The voice of Kegon Fall and other words in verse and song. Dedicated to the students of Japan', 686, 8, 18, 2023, '1 p. l., 28 p. O On cover: illus'),
		(1495, '1157930700', 9, 'A text-book of organic chemistry;', 2990, 9, 19, 1911, 'viii, 505 p. 24 cm'),
		(491, '1157459251', 10, 'A String of pearls : designed for the instruction and encouragement of young Latter-day Saints', 982, 10, 20, 1882, 'Flake'),
		(994, '1157796010', 1, 'Some official correspondence of George Canning [1821-1827];', 1988, 1, 21, 1887, '2 v. 23 cm'),
		(1924, '1157672342', 2, 'Some parallel formations in English', 3848, 2, 22, 1913, '72 p. 24 cm'),
		(539, '4995733180', 3, 'Songs of the lowly, and other poems', 1078, 3, 23, 1892, 'vii, 9-241 p. 21 cm'),
		(1807, '1157734060', 4, 'Songs of the day and night; or, Original hymns for public and private praise and reading. The life-story of Jesus Christ--a cantata; with other sacred poems', 3614, 4, 24, 1891, '285 p'),
		(430, '1085612630', 5, 'Stories and tales', 860, 5, 25, 1910, 'Vol. 4'),
		(327, '1158189686', 6, 'Verses', 654, 6, 26, 1890, 'vii, 125 p. ; 17 cm'),
		(364, '1158034304', 7, 'Union and peace! How they shall be restored : Speech of Hon. Charles Sumner, before the Republican state convention, at Worcester, October 1, 1861', 728, 7, 27, 1861, '8 p. 25 cm Caption book_name Electronic reproduction'),
		(558, '9999999999', 8, 'A treatise on the common sole (Solea vulgaris), considered both as an organism and as a commodity', 1116, 8, 28, 1890, 'viii, 147 p., 18 leaves of plates : 32 cm'),
		(296, '1084569027', 9, 'Rural organization', 592, 9, 29, 1921, '250 p. 20 cm'),
		(782, '1084591975', 10, 'Rule and misrule of the English in America; by the author of Sam Slick the clock-maker', 1564, 10, 30, 1851, '1 p. L., [xi]-xii, [13]-379p. 21 cm Also issued under book_name: The English in America'),
		(492, '1157817890', 1, 'Studies in citizenship for recruits', 984, 1, 31, 1922, '143 p. ; 23 cm'),
		(927, '1157566517', 2, 'Studies in the construction of dams: earthen and masonry. Arr. on the principle of question and answer for engineering students and others', 1854, 2, 32, 1919, '43 p. 8vo'),
		(620, '1085625427', 3, 'Tariff and tax commission', 1240, 3, 33, 1882, '24 p. ; 21 cm'),
		(472, '1085669501', 4, 'The three venerable ladies of England on church politics: Madam Britannia, Mother Church, and the Old Lady in Threadneedle Street', 944, 4, 34, 1874, '237 p'),
		(504, '1049690716', 5, 'Main-travelled roads; being six stories of the Mississippi Valley', 1008, 5, 35, 1893, null),
		(494, '1049656828', 6, 'Maurice Dering, or, The quadrilateral : a novel', 988, 6, 36, 1864, '2 v. ; 19 cm'),
		(404, '1048793049', 7, 'Mary in California', 808, 7, 37, 1922, 'viii p., 2 l., 242 p. 20 cm Plates printed on both sides'),
		(514, '1049678497', 8, 'The masquerader; a novel', 1028, 8, 37, 1904, '327 p. 20 cm'),
		(309, '1049650320', 9, 'Masollam :', 618, 9, 38, 1886, '3 v. 20 cm'),
		(586, '1049650808', 10, 'The mustee; or, Love and liberty', 1172, 10, 38, 1859, '[1] L., 5-487, [4] p. 20 cm Wright II, 1956 Pub. advts. (4 p.) at end'),
		(567, '1050788164', 1, 'The philosophy of the human voice: embracing its physiological history', 1134, 1, 39, 1855, 'xlviii, [49]-559 p. 23 cm'),
		(1228, '1050761342', 2, 'Pennsylvania at Chickamauga and Chattanooga', 2456, 2, 39, 1900, 'George W. Skinner, secretary of the Executive committee of the Commission, editor and compiler'),
		(319, '1050232421', 3, 'The opened shutters : a novel', 638, 3, 40, 1906, null),
		(1287, '1049673249', 4, 'Motor vehicle transportation', 2574, 4, 40, 1922, '696 p'),
		(729, '2597888810', 5, 'The wholesale grocery business in January, 1921', 1458, 5, 41, 1921, '12 p 19 cm'),
		(527, '1049681028', 6, 'The magic shadow show', 1054, 6, 41, 1913, '32 p'),
		(758, '6977145820', 7, 'Decay of rationalism', 1516, 7, 41, 1910, 'Thesis (Ph.D.)--University of Pennsylvania, 1910'),
		(1022, '1042944485', 8, 'Descriptive astronomy; an elementary exposition of the facts, principles, and theories of astronomical science', 2044, 8, 42, 1912, null),
		(942, '1048794371', 9, 'Mental physiology, especially in its relations to mental disorders', 1884, 9, 42, 1895, 'xv, 552 p'),
		(637, '1040007067', 10, 'A ragged register (of people, places and opinions).', 1274, 10, 42, 1879, null)
;
INSERT INTO wishlists ( user_id_fkey, wishlist_name ) VALUES
		(1, 'my documentary wishlist 1'),
		(2, 'my comedy wishlist 1'),
		(3, 'my war wishlist 1'),
		(4, 'my animation wishlist 1'),
		(5, 'my drama wishlist 1'),
		(6, 'my action wishlist 1'),
		(7, 'my fantasy wishlist 1'),
		(8, 'my sci-fi wishlist 1'),
		(9, 'my crime wishlist 1'),
		(10, 'my horror wishlist 1'),
		(11, 'my documentary wishlist 1'),
		(12, 'my comedy wishlist 1'),
		(13, 'my war wishlist 1'),
		(14, 'my animation wishlist 1'),
		(15, 'my drama wishlist 1'),
		(16, 'my action wishlist 1'),
		(17, 'my fantasy wishlist 1'),
		(18, 'my sci-fi wishlist 1'),
		(19, 'my crime wishlist 1'),
		(20, 'my horror wishlist 1'),
		(21, 'my documentary wishlist 1'),
		(22, 'my comedy wishlist 1'),
		(23, 'my war wishlist 1'),
		(24, 'my animation wishlist 1'),
		(25, 'my drama wishlist 1'),
		(26, 'my action wishlist 1'),
		(27, 'my fantasy wishlist 1'),
		(28, 'my sci-fi wishlist 1'),
		(29, 'my crime wishlist 1'),
		(30, 'my horror wishlist 1'),
		(31, 'my documentary wishlist 1'),
		(32, 'my comedy wishlist 1'),
		(33, 'my war wishlist 1'),
		(34, 'my animation wishlist 1'),
		(35, 'my drama wishlist 1'),
		(36, 'my action wishlist 1'),
		(37, 'my fantasy wishlist 1'),
		(38, 'my sci-fi wishlist 1'),
		(39, 'my crime wishlist 1'),
		(40, 'my horror wishlist 1'),
		(41, 'my documentary wishlist 1'),
		(42, 'my comedy wishlist 1'),
		(43, 'my war wishlist 1'),
		(44, 'my animation wishlist 1'),
		(45, 'my drama wishlist 1'),
		(46, 'my action wishlist 1'),
		(47, 'my fantasy wishlist 1'),
		(48, 'my sci-fi wishlist 1'),
		(49, 'my crime wishlist 1'),
		(50, 'my horror wishlist 1'),
		(1, 'my comedy wishlist 2'),
		(2, 'my war wishlist 2'),
		(3, 'my animation wishlist 2'),
		(4, 'my drama wishlist 2'),
		(5, 'my action wishlist 2'),
		(6, 'my fantasy wishlist 2'),
		(7, 'my sci-fi wishlist 2'),
		(8, 'my crime wishlist 2'),
		(9, 'my horror wishlist 2'),
		(10, 'my documentary wishlist 2'),
		(11, 'my comedy wishlist 2'),
		(12, 'my war wishlist 2'),
		(13, 'my animation wishlist 2'),
		(14, 'my drama wishlist 2'),
		(15, 'my action wishlist 2'),
		(16, 'my fantasy wishlist 2'),
		(17, 'my sci-fi wishlist 2'),
		(18, 'my crime wishlist 2'),
		(19, 'my horror wishlist 2'),
		(20, 'my documentary wishlist 2'),
		(21, 'my comedy wishlist 2'),
		(22, 'my war wishlist 2'),
		(23, 'my animation wishlist 2'),
		(24, 'my drama wishlist 2'),
		(25, 'my action wishlist 2')
;
INSERT INTO books_wishlists_lt ( wishlist_id_fkey, book_id_fkey ) VALUES
		(1, 1),
		(1, 2),
		(1, 3),
		(2, 2),
		(2, 3),
		(2, 4),
		(3, 3),
		(3, 4),
		(3, 5),
		(4, 4),
		(4, 5),
		(4, 6),
		(5, 5),
		(5, 6),
		(5, 7),
		(6, 6),
		(6, 7),
		(6, 8),
		(7, 7),
		(7, 8),
		(7, 9),
		(8, 8),
		(8, 9),
		(8, 10),
		(9, 9),
		(9, 10),
		(9, 11),
		(10, 10),
		(10, 11),
		(10, 12),
		(11, 11),
		(11, 12),
		(11, 13),
		(12, 12),
		(12, 13),
		(12, 14),
		(13, 13),
		(13, 14),
		(13, 15),
		(14, 14),
		(14, 15),
		(14, 16),
		(15, 15),
		(15, 16),
		(15, 17),
		(16, 16),
		(16, 17),
		(16, 18),
		(17, 17),
		(17, 18),
		(17, 19),
		(18, 18),
		(18, 19),
		(18, 20),
		(19, 19),
		(19, 20),
		(19, 21),
		(20, 20),
		(20, 21),
		(20, 22),
		(21, 21),
		(21, 22),
		(21, 23),
		(22, 22),
		(22, 23),
		(22, 24),
		(23, 23),
		(23, 24),
		(23, 25),
		(24, 24),
		(24, 25),
		(24, 26),
		(25, 25),
		(25, 26),
		(25, 27),
		(26, 26),
		(26, 27),
		(26, 28),
		(27, 27),
		(27, 28),
		(27, 29),
		(28, 28),
		(28, 29),
		(28, 30),
		(29, 29),
		(29, 30),
		(29, 31),
		(30, 30),
		(30, 31),
		(30, 32),
		(31, 31),
		(31, 32),
		(31, 33),
		(32, 32),
		(32, 33),
		(32, 34),
		(33, 33),
		(33, 34),
		(33, 35),
		(34, 34),
		(34, 35),
		(34, 36),
		(35, 35),
		(35, 36),
		(35, 37),
		(36, 36),
		(36, 37),
		(36, 38),
		(37, 37),
		(37, 38),
		(37, 39),
		(38, 38),
		(38, 39),
		(38, 40),
		(39, 39),
		(39, 40),
		(39, 41),
		(40, 40),
		(40, 41),
		(40, 42),
		(41, 41),
		(41, 42),
		(41, 43),
		(42, 42),
		(42, 43),
		(42, 44),
		(43, 43),
		(43, 44),
		(43, 45),
		(44, 44),
		(44, 45),
		(44, 46),
		(45, 45),
		(45, 46),
		(45, 47),
		(46, 46),
		(46, 47),
		(46, 48),
		(47, 47),
		(47, 48),
		(47, 49),
		(48, 48),
		(48, 49),
		(48, 50),
		(49, 49),
		(49, 50),
		(49, 1),
		(50, 50),
		(50, 1),
		(50, 2),
		(51, 1),
		(51, 2),
		(51, 3),
		(52, 2),
		(52, 3),
		(52, 4),
		(53, 3),
		(53, 4),
		(53, 5),
		(54, 4),
		(54, 5),
		(54, 6),
		(55, 5),
		(55, 6),
		(55, 7),
		(56, 6),
		(56, 7),
		(56, 8),
		(57, 7),
		(57, 8),
		(57, 9),
		(58, 8),
		(58, 9),
		(58, 10),
		(59, 9),
		(59, 10),
		(59, 11),
		(60, 10),
		(60, 11),
		(60, 12),
		(61, 11),
		(61, 12),
		(61, 13),
		(62, 12),
		(62, 13),
		(62, 14),
		(63, 13),
		(63, 14),
		(63, 15),
		(64, 14),
		(64, 15),
		(64, 16),
		(65, 15),
		(65, 16),
		(65, 17),
		(66, 16),
		(66, 17),
		(66, 18),
		(67, 17),
		(67, 18),
		(67, 19),
		(68, 18),
		(68, 19),
		(68, 20),
		(69, 19),
		(69, 20),
		(69, 21),
		(70, 20),
		(70, 21),
		(70, 22),
		(71, 21),
		(71, 22),
		(71, 23),
		(72, 22),
		(72, 23),
		(72, 24),
		(73, 23),
		(73, 24),
		(73, 25),
		(74, 24),
		(74, 25),
		(74, 26),
		(75, 25),
		(75, 26),
		(75, 27)
;
INSERT INTO reviews ( rating, comment, book_id_fkey, user_id_fkey ) VALUES
		(5, 'A fascinating insight into the life of Philip Doddridge.', 1, 1),
		(4, 'Well-written biography with great historical context.', 1, 2),
		(4, 'Interesting travel memoir.', 2, 2),
		(4, 'Provides a unique perspective on Dahomey.', 2, 3),
		(5, 'An inspiring read about the fight for liberty.', 3, 3),
		(4, 'Detailed account of a pivotal historical figure.', 3, 4),
		(4, 'Fascinating exploration of linguistic connections.', 4, 4),
		(4, 'Insightful analysis of language and culture.', 4, 5),
		(5, 'Captivating journey through Eastern Europe.', 5, 5),
		(5, 'Interesting blend of travel and sports anecdotes.', 5, 6),
		(4, 'Engaging account of the theatrical world.', 6, 6),
		(5, 'A must-read for theater lovers.', 6, 7),
		(4, 'Insightful reflections on historical periods.', 7, 7),
		(5, 'A thought-provoking journey through time.', 7, 8),
		(4, 'Informative overview of medical principles.', 8, 8),
		(4, 'Useful reference for understanding medicine.', 8, 9),
		(5, 'A captivating love story that keeps you hooked.', 9, 9),
		(5, 'Heartwarming tale of romance and passion.', 9, 10),
		(5, 'Beautiful poetry collection with profound themes.', 10, 10),
		(4, 'A delightful read for poetry enthusiasts.', 10, 11),
		(4, 'Insightful examination of Bismarcks era.', 11, 11),
		(4, 'A comprehensive analysis of historical events.', 11, 12),
		(5, 'In-depth exploration of trade routes and their impact.', 12, 12),
		(5, 'Fascinating insights into the economic history of the region.', 12, 13),
		(5, 'Insightful report on deaf-mute instruction at the Vienna Exhibition.', 13, 13),
		(5, 'Important documentation of educational practices.', 13, 14),
		(4, 'Interesting insights into the character of Octavia.', 14, 14),
		(4, 'A valuable addition to Shakespearean studies.', 14, 15),
		(5, 'Empowering and motivating read.', 15, 15),
		(5, 'Practical advice for personal growth and development.', 15, 16),
		(5, 'Charming tale with a heartwarming message.', 16, 16),
		(5, 'A delightful story about the quest for a tortoise-shell.', 16, 17),
		(5, 'Moving collection of poems about war.', 17, 17),
		(4, 'Evocative and thought-provoking poetry.', 17, 18),
		(5, 'Beautiful tribute to Japanese culture.', 18, 18),
		(5, 'Wonderful collection of verse and song.', 18, 19),
		(5, 'Comprehensive and well-explained textbook.', 19, 19),
		(5, 'An essential resource for students of organic chemistry.', 19, 20),
		(4, 'Uplifting and inspirational read.', 20, 20),
		(5, 'Encouraging messages for young believers.', 20, 21),
		(5, 'Insightful glimpse into historical correspondence.', 21, 21),
		(5, 'Fascinating read for those interested in political history.', 21, 22),
		(5, 'In-depth analysis of English language formations.', 22, 22),
		(5, 'A valuable resource for understanding linguistic structures.', 22, 23),
		(5, 'Heartfelt poetry that resonates with the soul.', 23, 23),
		(5, 'Powerful collection of poems reflecting on social issues.', 23, 24),
		(5, 'Beautiful hymns that inspire worship and reflection.', 24, 24),
		(5, 'Sacred poetry that touches the heart.', 24, 25),
		(5, 'Engaging and imaginative tales for all ages.', 25, 25),
		(5, 'Entertaining collection of stories with intriguing plots.', 25, 26),
		(5, 'Thought-provoking verses that stir the imagination.', 26, 26),
		(4, 'A poetic journey through emotions and experiences.', 26, 27),
		(4, 'Insightful speech advocating for unity and peace.', 27, 27),
		(4, 'A historical perspective on the restoration of union and peace.', 27, 28),
		(5, 'Comprehensive study of the common sole and its significance.', 28, 28),
		(5, 'Informative treatise on the biology and economic importance of the common sole.', 28, 29),
		(5, 'Insightful exploration of rural development.', 29, 29),
		(4, 'A valuable resource for rural community planning.', 29, 30),
		(5, 'Critical examination of English influence in America.', 30, 30),
		(4, 'Insightful analysis of colonial history.', 30, 31),
		(5, 'Informative guide for understanding citizenship responsibilities.', 31, 31),
		(4, 'A useful resource for promoting civic participation.', 31, 32),
		(5, 'Comprehensive study guide for dam construction.', 32, 32),
		(5, 'A practical approach to understanding dam engineering.', 32, 33),
		(5, 'Insightful analysis of tariff and tax policies.', 33, 33),
		(4, 'A valuable resource for understanding economic regulations.', 33, 34),
		(5, 'Insightful examination of the intersection of politics and religion.', 34, 34),
		(4, 'A thought-provoking study of church politics in England.', 34, 35),
		(5, 'Compelling stories that capture the essence of the Mississippi Valley.', 35, 35),
		(4, 'An authentic portrayal of life in the Midwest.', 35, 36),
		(5, 'Engaging novel with well-developed characters.', 36, 36),
		(4, 'A captivating story set against the backdrop of political intrigue.', 36, 37),
		(5, 'Marys journey through California was both exciting and enlightening.', 37, 37),
		(4, 'A delightful blend of adventure and romance. California comes alive in this book!', 37, 38),
		(5, 'The masquerade of identities kept me guessing until the very end. Brilliant!', 38, 38),
		(5, 'An enthralling read with twists and turns at every corner. Highly recommend!', 38, 39),
		(4, 'While lengthy, Masollam offers a rich tapestry of characters and settings.', 39, 39),
		(4, 'A classic work with deep philosophical undertones. Not for the faint-hearted.', 39, 40),
		(5, 'A poignant tale of love and freedom. The characters stayed with me long after I finished.', 40, 40),
		(4, 'An inspiring story that highlights the resilience of the human spirit. Loved it!', 40, 41),
		(5, 'A fascinating exploration of the human voice. Insightful and engaging!', 41, 41),
		(4, 'An essential read for anyone interested in understanding the voices significance in human communication.', 41, 42),
		(5, 'An invaluable account of Pennsylvanias contributions to these pivotal battles. A masterpiece of historical scholarship!', 42, 42),
		(5, 'Skinners thorough research and compelling narrative make this a must-read for Civil Waraficionados.', 42, 43),
		(4, 'An insightful exploration of societal norms and individual identity. Thought-provoking!', 43, 43),
		(4, 'While the premise was promising, the execution fell short for me. Still worth a read for its themes.', 43, 44),
		(5, 'An exhaustive study of motor vehicle transportation. Comprehensive and enlightening!', 44, 44),
		(5, 'This book is a treasure trove of information for anyone interested in the evolution of transportation systems.', 44, 45),
		(5, 'Insightful and informative. A must-read for anyone in the wholesale grocery industry!', 45, 45),
		(5, 'Provides valuable insights into the dynamics of the wholesale grocery business. Well-researched and engaging.', 45, 46),
		(5, 'A whimsical journey into the world of magic. Enchanting and delightful!', 46, 46),
		(5, 'Captivating storytelling with vivid imagery. Children will love this magical adventure!', 46, 47),
		(5, 'An insightful examination of the decline of rationalist thought. Thought-provoking and meticulously argued!', 47, 47),
		(4, 'Raises important questions about the limits of rationalism. A stimulating read for those interested in philosophy.', 47, 48)
;
INSERT INTO shopping_carts_lt ( user_id_fkey, book_id_fkey, quantity ) VALUES
		(1, 1, 7),
		(1, 2, 6),
		(1, 3, 5),
		(1, 4, 4),
		(1, 5, 3),
		(2, 1, 7),
		(2, 2, 6),
		(2, 3, 5),
		(2, 4, 4),
		(2, 5, 3),
		(3, 1, 7),
		(3, 2, 6),
		(3, 3, 5),
		(3, 4, 4),
		(3, 5, 3),
		(4, 1, 7),
		(4, 2, 6),
		(4, 3, 5),
		(4, 4, 4),
		(4, 5, 3),
		(5, 1, 7),
		(5, 2, 6),
		(5, 3, 5),
		(5, 4, 4),
		(5, 5, 3),
		(6, 1, 7),
		(6, 2, 6),
		(6, 3, 5),
		(6, 4, 4),
		(6, 5, 3),
		(7, 1, 7),
		(7, 2, 6),
		(7, 3, 5),
		(7, 4, 4),
		(7, 5, 3),
		(8, 1, 7),
		(8, 2, 6),
		(8, 3, 5),
		(8, 4, 4),
		(8, 5, 3),
		(9, 1, 7),
		(9, 2, 6),
		(9, 3, 5),
		(9, 4, 4),
		(9, 5, 3),
		(10, 1, 7),
		(10, 2, 6),
		(10, 3, 5),
		(10, 4, 4),
		(10, 5, 3)
;